# Generated by Django 3.2.5 on 2021-07-26 11:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SentRequests',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('unit_code', models.CharField(max_length=50)),
                ('customer_id', models.CharField(max_length=30)),
                ('api_request', models.CharField(max_length=20)),
                ('api_content', models.CharField(max_length=50)),
                ('notes', models.CharField(max_length=100)),
            ],
        ),
    ]
