# Generated by Django 3.2.5 on 2021-07-26 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('singlepage', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sentrequests',
            name='api_content',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='sentrequests',
            name='notes',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
