# Generated by Django 3.2.5 on 2021-07-26 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('singlepage', '0002_auto_20210726_1127'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sentrequests',
            name='api_request',
            field=models.IntegerField(max_length=20),
        ),
    ]
