# Generated by Django 3.2.5 on 2021-07-26 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('singlepage', '0003_alter_sentrequests_api_request'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sentrequests',
            name='api_request',
            field=models.IntegerField(),
        ),
    ]
