# Generated by Django 3.2.5 on 2021-07-29 15:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('singlepage', '0004_alter_sentrequests_api_request'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sentrequests',
            name='api_content',
        ),
    ]
