# Generated by Django 3.2.5 on 2021-07-29 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('singlepage', '0005_remove_sentrequests_api_content'),
    ]

    operations = [
        migrations.AddField(
            model_name='sentrequests',
            name='api_content',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
